### ISSUE TITLE
configurable handlers

### ISSUE THREAD

**Issue by xLink** [troolee/gridstack.js#108]
i see in #89 that you added a way to remove/hide a widget.

i think we need a configurable way to customize the handlers on the widget itself, so you can add one to remove the widget, or even add an options hander to change settings for that widget etc

**Comment by troolee** [comment]
Gridstack doesn't care what widgets are, what is header or something else. I don't think the functionality you're talking about should be a part of gridstack. It's just about layout.

**Comment by xLink** [comment]
the only handler you have there is one for the resizing, i believe it would be infinately better to set a handler set and a small api to allow extensibility from outside

its just reworking the functionality that is there currently for a better dev experience

**Comment by nWidart** [comment]
I'd like something like this too.

**Comment by xLink** [comment]
@troolee the examples @nWidart posted are what i wish for the configurable handlers, all you need to do is change the api slightly & make the resizable handler use the extendibility. We can add more programatically then.

**Comment by xLink** [comment]
Bump, @troolee is there any way we are gonna get configurable handlers?

**Comment by troolee** [comment]
Please check the documentation https://github.com/troolee/gridstack.js#options

**Comment by xLink** [comment]
The options you provide there do not help. I want to be able to add handlers to support removing the widget, and an options modal. Having a configurable handler setup will make customizations much more developer friendly, and allow for other handlers like minimize / maximizing widgets for eg

**Comment by troolee** [comment]
Again, that what you are talking about is park of user content. Gridstack is layout library, not content. You need to implement that by yourself.

Someone needs button and popup menu, other one toolbar with buttons, other — toolbar with checkboxes. That's why there is no reason to implement this. 

You need to create yours widgets from templates or so using js. It's really easy with knockout for instance.

**Comment by pySilver** [comment]
@troolee totally agree – this is easy to implement and out of this library responsability. Close button is simple, here is an exaple for those who are interested:

```css
.grid-stack-item {
    cursor: move;

    .gs-close-handle {
      opacity: 0;
      width: 15px;
      height: 15px;
      top: 4px;
      left: 4px;
      background-image: url('data:image/svg+xml;base64,PHN2ZyB2aWV3Qm94PSIwIDAgNTAwIDUwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48Y2lyY2xlIGN4PSIyNDkuOSIgY3k9IjI1MC40IiByPSIyMDQuNyIgc3Ryb2tlPSIjMDAwIiBzdHJva2UtbWl0ZXJsaW1pdD0iMTAiLz48Y2lyY2xlIGN4PSIyNDkuOSIgY3k9IjI0Ny40IiBmaWxsPSIjRkZGIiByPSIxODEuOCIgc3Ryb2tlPSIjMDAwIiBzdHJva2UtbWl0ZXJsaW1pdD0iMTAiLz48cGF0aCBmaWxsPSJub25lIiBzdHJva2U9IiMwMDAiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgc3Ryb2tlLW1pdGVybGltaXQ9IjEwIiBzdHJva2Utd2lkdGg9IjIyIiBkPSJNMTYyIDE1OS41bDE3NS44IDE3NS44TTMzNy44IDE1OS41TDE2MiAzMzUuMyIvPjwvc3ZnPg==');
      background-position: top left;
      background-repeat: no-repeat;
      z-index: 90;
      cursor: pointer;
      position: absolute;
      transition: opacity 300ms ease 50ms,background-color 300ms ease 50ms;
    }

    .ui-resizable-se {
      width: 15px;
      height: 15px;
      bottom: 0;
      right: 2px;
      background-color: #e6e6e6;
      background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSJubyI/Pg08IS0tIEdlbmVyYXRvcjogQWRvYmUgRmlyZXdvcmtzIENTNiwgRXhwb3J0IFNWRyBFeHRlbnNpb24gYnkgQWFyb24gQmVhbGwgKGh0dHA6Ly9maXJld29ya3MuYWJlYWxsLmNvbSkgLiBWZXJzaW9uOiAwLjYuMSAgLS0+DTwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+DTxzdmcgaWQ9IlVudGl0bGVkLVBhZ2UlMjAxIiB2aWV3Qm94PSIwIDAgNiA2IiBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjojZmZmZmZmMDAiIHZlcnNpb249IjEuMSINCXhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHhtbDpzcGFjZT0icHJlc2VydmUiDQl4PSIwcHgiIHk9IjBweCIgd2lkdGg9IjZweCIgaGVpZ2h0PSI2cHgiDT4NCTxnIG9wYWNpdHk9IjAuMzAyIj4NCQk8cGF0aCBkPSJNIDYgNiBMIDAgNiBMIDAgNC4yIEwgNCA0LjIgTCA0LjIgNC4yIEwgNC4yIDAgTCA2IDAgTCA2IDYgTCA2IDYgWiIgZmlsbD0iIzAwMDAwMCIvPg0JPC9nPg08L3N2Zz4=');
      background-position: center center;
      background-repeat: no-repeat;
      cursor: se-resize;
      position: absolute;
      transform: none;
      transition: opacity 300ms ease 50ms,background-color 300ms ease 50ms;

      &:before {
        content: normal;
      }
    }

    .ui-resizable-sw {
      @extend .ui-resizable-se;
      left: 2px;
      bottom: 0;
      right: auto;
      cursor: sw-resize;
      transform: rotate(90deg);
    }

    // show close/resize handles and overlays while interacting with item (drag, resize, hover)
    &:hover, &.ui-draggable-dragging, &.ui-resizable-resizing {
      .gs-close-handle {
        opacity: 1 !important;
      }

      .drag-overlay {
        opacity: .8 !important;
        background: #fff;
      }
    }

  }
```

widget template should have "close" handler
```html
<script id="item-video" type="text/x-template">
  <div class="grid-stack-item" data-gs-width="2" data-gs-height="24" data-gs-auto-position="yes" data-gs-max-height="40" data-gs-min-height="24" data-gs-max-width="4" data-gs-min-width="2">
    <div class="grid-stack-item-content">
      <div class="my-widget">
        <div class="drag-overlay"></div>
        <iframe width="100%" height="100%" src="https://www.youtube.com/embed/bVXMXZY2Bas?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
      </div>
      <span class="gs-close-handle"></span>
    </div>
  </div>
</script>
```

```js
$grid.on('click', '.gs-close-handle', function(){
    var el = $(this).parents('.grid-stack-item');
    el.fadeOut(200, function(){
      gridInstance.remove_widget(el, true);
    });
  });
```
