### ISSUE TITLE
min_width needs better docs

### ISSUE THREAD

**Issue by pySilver** [troolee/gridstack.js#174]
Hi!,
Docs says:
- `min_width` - minimal width. If window width is less, grid will be shown in one-column mode (default: `768`)

However, thats not true. Without overriding CSS media query, lesser values won't be taken into account (yeah, grid will be locked, but it still goes one column mode earlier than expeced)
```css
# responsible line
@media (max-width: 768px) {}
```

I'm not really sure, but something like might help:

```javascript
document.querySelector('style').textContent +=
    "@media (max-width: 768px) { .grid-stack-item { /*undo styles?*/ }}"
```

**Comment by josephndenton** [comment]
Saw this issue as well. Was able to fix it to generate the media query based on the value of min_width with:

```css
/* Comment this portion out of the CSS */
/*
@media (max-width: 768px) {
  .grid-stack-item {
    position: relative !important;
    width: auto !important;
    left: 0 !important;
    top: auto !important;
    margin-bottom: 20px;
  }
  .grid-stack-item .ui-resizable-handle {
    display: none;
  }

  .grid-stack {
    height: auto !important;
  }
}
*/
```

```javascript 
GridStack.prototype._update_styles = function (max_height) {
...
    // Add this line below to the bottom of GridStack.prototype._update_styles to update the media query to the value of min_width
    Utils.insert_css_rule(this._styles, '@media (max-width: ' + this.opts.min_width + 'px)', '.grid-stack-item { position: relative !important; width: auto !important; left: 0 !important; top: auto !important; margin-bottom: $vertical_padding; } .grid-stack-item .ui-resizable-handle { display: none; } .grid-stack { height: auto !important; }', 0);

};
```
