### ISSUE TITLE
Improvement Suggestion

### ISSUE THREAD

**Issue by ascendantofrain** [troolee/gridstack.js#81]
Just a little something I made for my own project using this framework.

I use SASS with my application and using this little snippet makes adjusting grids MUCH easier.

```sass
.grid-stack-item {

    $gridstack-columns: 12;

    @for $i from 1 through $gridstack-columns {
        &[data-gs-width='#{$i}'] { width: (100% / $gridstack-columns) * $i; }
        &[data-gs-x='#{$i}'] { left: (100% / $gridstack-columns) * $i; }
        &.grid-stack-item[data-gs-min-width='#{$i}'] { min-width: (100% / $gridstack-columns) * $i; }
        &.grid-stack-item[data-gs-max-width='#{$i}'] { max-width: (100% / $gridstack-columns) * $i; }
    }
}
```

**Comment by troolee** [comment]
I've update README with your snippet. Thank you.

**Comment by abologna-r7** [comment]
Late to the conversation but you might also want to have the width variable, either in percentage or pixels, since being responsive and fluid not always works hand to hand... One thing is to have a responsive container, and another one is to have a responsive widget so sometimes having pixel dimensions is not a bad idea.

So if you put that logic inside a media query you can have different pixel/percentage based widgets sizes.

```
            $gridstack-columns: 12;
            $grdistack-width: 1440px;

            @for $i from 1 through $gridstack-columns {
               &[data-gs-width='#{$i}'] { width: ($grdistack-width / $gridstack-columns) * $i; }
               &[data-gs-x='#{$i}'] { left: ($grdistack-width / $gridstack-columns) * $i; }
               &.grid-stack-item[data-gs-min-width='#{$i}'] { min-width: ($grdistack-width / $gridstack-columns) * $i; }
               &.grid-stack-item[data-gs-max-width='#{$i}'] { max-width: ($grdistack-width / $gridstack-columns) * $i; }
            }
```

**Comment by cspeer** [comment]
Here is a less css version:

```less
@columns: 6;
.gs-item(@n) when (@n > 0) {
  .gs-item(@n - 1);
  
  &[data-gs-width="@{n}"] { width: (100% / @columns) * @n; }
  &[data-gs-x="@{n}"] { left: (100% / @columns) * @n; }
  &.grid-stack-item[data-gs-min-width="@{n}"] { min-width: (100% / @columns) * @n; }
  &.grid-stack-item[data-gs-max-width="@{n}"] { max-width: (100% / @columns) * @n; }
}

.grid-stack-item {
  .gs-item(@columns);
}
```
